services:
  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - USER=transmission
      - PASS=lesFritesDelicieuses
    volumes:
      - /home/transmission/data:/config
      - downloads-volume:/downloads
      - watch-volume:/watch
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped

  seedbox:
    image: seedbox
    container_name: seedbox
    ports:
      - 3000:3000
    volumes:
      - downloads-volume:/app/downloads
      - watch-volume:/app/watch
    depends_on:
      - transmission

volumes:
  downloads-volume:
    driver: local
  watch-volume:
    driver: local
